// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAf-FEglMdC_WnklNlzgZy8YhNnsQi93g',
    appId: '1:597211732493:web:f0bb60372016ab4111d344',
    messagingSenderId: '597211732493',
    projectId: 'puskazzapp',
    authDomain: 'puskazzapp.firebaseapp.com',
    storageBucket: 'puskazzapp.appspot.com',
    measurementId: 'G-ZTTY64KQMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbuzZnrQYsjmo6kMA3eBhrF6BjaiY6uXc',
    appId: '1:597211732493:android:a407b632e41baf3211d344',
    messagingSenderId: '597211732493',
    projectId: 'puskazzapp',
    storageBucket: 'puskazzapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp1vIrh0oahy7oaSS1uhFXJnLGhHtT8_U',
    appId: '1:597211732493:ios:55895a0ec881943311d344',
    messagingSenderId: '597211732493',
    projectId: 'puskazzapp',
    storageBucket: 'puskazzapp.appspot.com',
    iosClientId: '597211732493-843fmda9884c7eqpketjr52rp0u6pjck.apps.googleusercontent.com',
    iosBundleId: 'com.szeligbalazs.puskazzapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp1vIrh0oahy7oaSS1uhFXJnLGhHtT8_U',
    appId: '1:597211732493:ios:915e7da54c766a0911d344',
    messagingSenderId: '597211732493',
    projectId: 'puskazzapp',
    storageBucket: 'puskazzapp.appspot.com',
    iosClientId: '597211732493-kg3215qddavfjnq7n2rhb0666bcu135i.apps.googleusercontent.com',
    iosBundleId: 'com.example.puskazzApp.RunnerTests',
  );
}
